### PR TITLE
Disabled useNewHomePage setting

### LINKED ISSUE #1125: [BUG] Setting home:useNewHomePage has  a buggy behavior
## Describe the bug

Setting `home:useNewHomePage` has a buggy behavior. The entire menu changes and stops responding in several items.

## To Reproduce

1. Go to '/app/management/opensearch-dashboards/settings'
2. Scroll down to 'Use New Home Page'
3. Click on 'home:useNewHomePage -> On'
4. The entire menu changes and stops responding in several items.

## Expected behavior
A menu layout different from the default.

## Environment
**OpenSearch Version**
Wazuh Indexer 4.14.3

**Dashboards Version**
Wazuh Indexer 4.14.3

**Plugins**

```
alertingDashboards@2.19.4.0
anomalyDetectionDashboards@2.19.4.0
customImportMapDashboards@2.19.4.0
ganttChartDashboards@2.19.4.0
indexManagementDashboards@2.19.4.0
notificationsDashboards@2.19.4.0
reportsDashboards@2.19.4.0
securityDashboards@2.19.4.0
wazuh@4.14.3-03
wazuhCheckUpdates@4.14.3-03
wazuhCore@4.14.3-03
```

**Screenshots**

Image

**Host/Environment (please complete the following information):**
 - OS: MacOS/Ubuntu/Win11
 - Browser and version [Chrome/Firefox latest versions]

**Additional context**
Related issue: https://github.com/wazuh/wazuh-dashboard/issues/280

### PR DESCRIPTION
**Pull request by Machi3mfl**
### Description

This PR changes:
- Hard-disabled home:useNewHomePage at source
In ui_settings.ts, the setting stays registered but it is now forced to false with schema.literal(false) and marked readonly: true.

- Ignored YAML overrides for that setting
In ui_settings_config.ts, a deprecation handler removes uiSettings.overrides."home:useNewHomePage" during config processing, so even if someone sets it in opensearch_dashboards.yml, startup does not fail and the feature remains disabled.

### Issues Resolved

#1125 

## Screenshot

Screenshot 2026-02-26 at 4 25 54 PM

## Testing the changes

1. UI check: setting is not visible

Open Management -> OpenSearch Dashboards -> Settings, search for home and Use New Home Page.
Expected result: home:useNewHomePage does not appear in Advanced Settings.

2. Dev Tools check: force persisted value to true

Run this in Dev Tools to find the config document:

```http
POST .kibana/_update/config:2.19.4?refresh=true
{
  "doc": {
    "config": {
      "home:useNewHomePage": true
    }
  }
}

GET .kibana*/_search?expand_wildcards=all&ignore_unavailable=true
{
  "query": {
    "ids": {
      "values": ["config:2.19.4"]
    }
  }
}
```

Screenshot 2026-02-26 at 4 40 04 PM

Expected result: dashboard still works, setting still not shown in UI, feature remains effectively disabled.

3. opensearch_dashboards.yml override check: service still starts and override is ignored
For security mode in this repo, edit opensearch_dashboards.dev.security.yml:

```yml
...
uiSettings:
  overrides:
    "home:useNewHomePage": true
...
```

Restart and start dashboard:

```bash
./docker/dev.sh down security
./docker/dev.sh up security
```

### Check List

- [x] All tests pass
  - [x] `yarn test:jest`
  - [x] `yarn test:jest_integration`
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by rodrigofez — COMMENTED** [review]
🟢  UI check: setting is not visible

image


🟢 Force persisted value to true, check dashboard still works, setting still not shown in UI, feature remains effectively disabled.

https://github.com/user-attachments/assets/fe69f4f3-cc8c-4d84-8496-57f99124d313


🟢  opensearch_dashboards.yml override check: service still starts and override is ignored

image

image

**Review by rodrigofez — CHANGES_REQUESTED** [review]
✅ LGTM, we're just missing the changelog entry

**Comment by Machi3mfl** [comment]
> ✅ LGTM, we're just missing the changelog entry

Updated on https://github.com/wazuh/wazuh-dashboard/pull/1132/commits/703098c333899e56d6910c0c4f5e62f0cea9ce4c

**Review by rodrigofez — DISMISSED** [review]

**Review by Ripdiegozz — DISMISSED** [review]
🟢  UI check: setting is not visible

Image

🟢 Force persisted value to true, check dashboard still works, setting still not shown in UI, feature remains effectively disabled.

https://github.com/user-attachments/assets/3dd372a0-93c5-46ec-8238-1d4b3ecdad8d

🟢  opensearch_dashboards.yml override check: service still starts and override is ignored

Image

**Review by FernandoCastilla — COMMENTED** [review]
🟢CR
🟢Tests

Image

**Review by FernandoCastilla — DISMISSED** [review]
🟢LGTM

File: src/core/server/ui_settings/ui_settings_config.ts [hunk 1]
```diff
@@ -28,13 +28,39 @@
...
+// update the setting definition in src/plugins/home/server/ui_settings.ts.
+const ignoreUseNewHomePageOverride: ConfigDeprecation = (settings, fromPath, log) => {
+  const settingPath = `${fromPath}.overrides.${USE_NEW_HOME_PAGE_SETTING}`;
+  if (get(settings, settingPath) === undefined) {
+    return settings;
+  }
+
+  unset(settings, settingPath);
+  log(
+    `"${settingPath}" is ignored in Wazuh because the new home page is not supported and remains disabled`
```
Comment (Desvelao) [inline src/core/server/ui_settings/ui_settings_config.ts]:
```suggestion
    `"${settingPath}" is ignored because the new home page is not supported and remains disabled`
```

File: CHANGELOG.md [hunk 2]
```diff
@@ -8,6 +8,10 @@ All notable changes to the Wazuh app project will be documented in this file.
 
 - Support for Wazuh 4.14.5
 
+### Changed
+
+- Disabled useNewHomePage setting [#1132](https://github.com/wazuh/wazuh-dashboard/pull/1132)
```
Comment (Desvelao) [inline CHANGELOG.md]:
```suggestion
- Disabled home:useNewHomePage setting [#1132](https://github.com/wazuh/wazuh-dashboard/pull/1132)
```

File: src/core/server/ui_settings/ui_settings_config.test.ts [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+    const { migrated, messages } = applyUiSettingsDeprecations({
+      overrides: {
+        'home:useNewHomePage': true,
+        'theme:version': 'v7',
+      },
+    });
+
+    expect(messages).toMatchInlineSnapshot(`
+      Array [
+        "\\"uiSettings.overrides.home:useNewHomePage\\" is ignored in Wazuh because the new home page is not supported and remains disabled",
```
Comment (Desvelao) [inline src/core/server/ui_settings/ui_settings_config.test.ts]:
```suggestion
        "\\"uiSettings.overrides.home:useNewHomePage\\" is ignored because the new home page is not supported and remains disabled",
```

**Comment by Desvelao** [comment]
# Test 
1. :green_circle: image

2. :green_circle: 
image

3. :green_circle: 
```
server    log   [07:35:08.723] [info][plugins-service] Plugin "applicationConfig" is disabled.
server    log   [07:35:08.727] [info][plugins-service] Plugin "cspHandler" is disabled.
server    log   [07:35:08.728] [info][plugins-service] Plugin "dataSource" is disabled.
server    log   [07:35:08.728] [info][plugins-service] Plugin "visTypeXy" is disabled.
server    log   [07:35:08.729] [info][plugins-service] Plugin "workspace" is disabled.
server    log   [07:35:08.750] [warning][config][deprecation] "uiSettings.overrides.home:useNewHomePage" is ignored because the new home page is not supported and remains disabled
server    log   [07:35:08.791] [info][dynamic-config-service] registering middleware to inject context to AsyncLocalStorage
[agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
```

**Review by Desvelao — APPROVED** [review]
